#!/usr/bin/env python3
"""
Post AI-analyzed pins to Pinterest through your real browser (no Pinterest API).

Reads pins with status='ready' (title + description already generated by the
analyzer) from the local SQLite DB, then for each one:
  - opens Pinterest's create-pin page in YOUR Chrome profile (already logged in)
  - uploads the image
  - fills Title / Description / Alt text / Board
  - clicks Publish
  - waits a randomized delay before the next pin

WARNING: automated posting through the Pinterest web UI likely violates
Pinterest's Terms of Service and may get the account flagged/suspended. Run at
your own risk, with delays and low volume.

SETUP
  1. pip install playwright
  2. playwright install chromium   (only needed if not using your system Chrome)
  3. Close Chrome, or already have it running with remote debugging (see --cdp).
  4. First run with --dry-run to verify selectors against your Pinterest UI
     without actually publishing.

RUN
  python scripts/post_via_browser.py --dry-run
  python scripts/post_via_browser.py --limit 5 --min-delay 45 --max-delay 120
"""

from __future__ import annotations

import argparse
import random
import sqlite3
import sys
import time
from pathlib import Path

try:
    from playwright.sync_api import sync_playwright
except ImportError:
    sys.exit("playwright not installed. Run: pip install playwright && playwright install chromium")

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_DB = REPO_ROOT / "pinterest_automation" / "data.db"
DEFAULT_TARGET = "https://www.pinterest.com/pin-builder/"

# Candidate selectors (Pinterest UI changes; verify in --dry-run).
TITLE_SELECTORS = [
    "input[placeholder*='title' i]",
    "textarea[placeholder*='title' i]",
    "[aria-label='Title']",
]
DESC_SELECTORS = [
    "textarea[placeholder*='description' i]",
    "[aria-label*='description' i]",
    "textarea[placeholder*='Tell everyone' i]",
]
ALT_SELECTORS = [
    "[aria-label*='alt text' i]",
    "input[placeholder*='alt text' i]",
    "textarea[placeholder*='alt text' i]",
]


def load_ready_pins(db_path: Path, limit: int | None, only_ids: list[int] | None) -> list[dict]:
    if not db_path.exists():
        sys.exit(f"DB not found: {db_path}")
    con = sqlite3.connect(str(db_path))
    con.row_factory = sqlite3.Row
    q = (
        "SELECT id, title, description, alt_text, board_name, image_path "
        "FROM pins WHERE status='ready' AND title IS NOT NULL AND image_path IS NOT NULL"
    )
    params: list = []
    if only_ids:
        q += " AND id IN (%s)" % ",".join("?" * len(only_ids))
        params = [str(i) for i in only_ids]
    q += " ORDER BY id"
    if limit:
        q += f" LIMIT {int(limit)}"
    rows = con.execute(q, params).fetchall()
    con.close()
    pins = []
    for r in rows:
        img = Path(r["image_path"])
        if not img.exists():
            print(f"  skip pin #{r['id']}: image missing ({r['image_path']})")
            continue
        pins.append({
            "id": r["id"],
            "title": r["title"],
            "description": r["description"] or "",
            "alt_text": r["alt_text"] or "",
            "board": r["board_name"] or "",
            "image": img,
        })
    return pins


def _first(page, selectors: list[str]):
    for sel in selectors:
        try:
            el = page.locator(sel).first
            if el.count() and el.is_visible(timeout=1500):
                return el
        except Exception:
            continue
    return None


def _type_human(el, text: str):
    el.click()
    el.fill("")
    for ch in text:
        el.type(ch, delay=random.randint(8, 28))


def fill_board(page, board: str, create: bool):
    if not board:
        return
    btn = page.get_by_text("Select a board", exact=False).first
    if btn.count():
        btn.click()
    search = _first(page, [
        "input[placeholder*='board' i]",
        "[aria-label*='board' i]",
    ])
    if not search:
        print("  ! board picker not found; leaving default board selection")
        return
    search.fill(board)
    time.sleep(random.uniform(0.8, 1.6))
    opt = page.locator(f"text={board}").first
    if opt.count():
        opt.click()
        print(f"  board: selected '{board}'")
    elif create:
        create_btn = page.get_by_text("Create board", exact=False).first
        if create_btn.count():
            create_btn.click()
            print(f"  board: created '{board}'")
    else:
        print(f"  ! board '{board}' not found and --no-create set; using default")


def post_pin(page, pin: dict, dry_run: bool) -> bool:
    print(f"Pin #{pin['id']}: {pin['title'][:50]!r} (board={pin['board'] or 'default'})")
    if "pin-builder" not in page.url:
        page.goto(DEFAULT_TARGET, wait_until="domcontentloaded")

    file_input = page.locator("input[type=file]").first
    if not file_input.count():
        print("  ! file input not found - aborting this pin")
        return False
    file_input.set_input_files(str(pin["image"]))
    time.sleep(random.uniform(1.5, 3.0))

    title_el = _first(page, TITLE_SELECTORS)
    if title_el:
        _type_human(title_el, pin["title"])
    else:
        print("  ! title field not found")

    desc_el = _first(page, DESC_SELECTORS)
    if desc_el:
        _type_human(desc_el, pin["description"])
    else:
        print("  ! description field not found")

    alt_el = _first(page, ALT_SELECTORS)
    if alt_el:
        _type_human(alt_el, pin["alt_text"])
    else:
        print("  - alt text field not found (skipped)")

    fill_board(page, pin["board"], create=False)

    if dry_run:
        page.screenshot(path=f"/tmp/pin_{pin['id']}_dryrun.png")
        print(f"  [dry-run] filled pin #{pin['id']}; screenshot saved, NOT published")
        return True

    publish = page.get_by_role("button", name="Publish", exact=False).first
    if not publish.count():
        publish = page.get_by_role("button", name="Create Pin", exact=False).first
    if not publish.count():
        print("  ! publish button not found - aborting")
        return False
    publish.click()
    print(f"  published pin #{pin['id']}")
    time.sleep(random.uniform(2.0, 4.0))
    return True


def main():
    ap = argparse.ArgumentParser(description="Post ready pins to Pinterest via your browser.")
    ap.add_argument("--db", type=Path, default=DEFAULT_DB)
    ap.add_argument("--limit", type=int, default=None)
    ap.add_argument("--only-ids", type=int, nargs="*", default=None)
    ap.add_argument("--min-delay", type=float, default=45.0, help="min seconds between pins")
    ap.add_argument("--max-delay", type=float, default=120.0, help="max seconds between pins")
    ap.add_argument("--dry-run", action="store_true", help="fill fields but do NOT publish")
    ap.add_argument("--profile", type=str, default=None,
                    help="Chrome user-data-dir to reuse your logged-in session")
    ap.add_argument("--cdp", type=str, default=None,
                    help="Connect to an already-running Chrome via CDP, e.g. http://localhost:9222")
    ap.add_argument("--headless", action="store_true")
    args = ap.parse_args()

    pins = load_ready_pins(args.db, args.limit, args.only_ids)
    if not pins:
        print("No ready pins to post.")
        return
    print(f"Loaded {len(pins)} ready pin(s). dry_run={args.dry_run}")

    with sync_playwright() as p:
        if args.cdp:
            browser = p.chromium.connect_over_cdp(args.cdp)
            context = browser.contexts[0]
        else:
            if not args.profile:
                print("No --profile given: launching a temporary profile (you'll need to log in).")
            context = p.chromium.launch_persistent_context(
                user_data_dir=args.profile or "",
                channel="chrome",
                headless=args.headless,
                args=["--no-first-run", "--disable-blink-features=AutomationControlled"],
            )
        page = context.pages[0] if context.pages else context.new_page()
        page.goto(DEFAULT_TARGET, wait_until="domcontentloaded")
        if "login" in page.url.lower() or page.get_by_text("Log in", exact=False).count():
            input("Looks like you're not logged in. Log in to Pinterest in the browser, then press Enter...")

        posted = 0
        for i, pin in enumerate(pins):
            try:
                if post_pin(page, pin, args.dry_run):
                    posted += 1
            except Exception as e:
                print(f"  ! error on pin #{pin['id']}: {e}")
            if i < len(pins) - 1 and not args.dry_run:
                delay = random.uniform(args.min_delay, args.max_delay)
                print(f"  waiting {delay:.0f}s before next pin...")
                time.sleep(delay)

        print(f"Done. {'[dry-run] ' if args.dry_run else ''}processed {posted}/{len(pins)} pin(s).")
        if not args.cdp:
            context.close()


if __name__ == "__main__":
    main()
